---
# The following python package is required for ansible to interact with
# the docker service to manage docker containers.
- name: Ensure python docker-py package is installed
  pip:
    name: docker-py

# When running a playbook, this step can take a while the first time 
# on a new image since it will be doing a `docker pull` in the background.
# You don't need to make any modifications here, but you'll need to
# read a bit on how variable precedence works with ansible
# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
# http://docs.ansible.com/ansible/docker_container_module.html
- name: Start/Restart the unh698 container
  docker_container:
    name: "unh698-{{ unh698_environment }}"
    image: "{{ unh698_image }}:{{ unh698_image_version }}"
    command: "{{ unh698_command }}"
    state: started
    ports:
     - "{{ unh698_host_port }}:{{ unh698_container_port }}"

# This should check that the container that is started in the last step
# is up and running by checking the localhost's webpage.
# Determine how to format the url used for the check.
# Hints:
#   A variable should be used in the url
#   http://docs.ansible.com/ansible/uri_module.html
- name: verify that webserver is running
  uri:
    url: xxxxxxx
    method: GET
