---
# The production version of docker-cloud-test should be the image that has just
# a main page with the 'UNH698 Website' text.  This version of the website
# should be available on port 8080 of your server.
- name: Deploy the production version of your website based on the previous tag of your docker-cloud-test image
  hosts: localhost
  become: true
  vars:
    unh698_environment: production
    unh698_image_version: xxxxxxx
    unh698_host_port: xxxxxxx
    unh698_container_port: xxxxxxx
  roles:
    - unh698
  