---
# The production version of docker-cloud-test should be the image that includes the website with
# your topic subpage.  This version of the website should be available on port 8081 of your server.
- name: Deploy the staging version of your website based on the newest tag of your docker-cloud-test image
  hosts: localhost
  become: true
  vars:
    unh698_environment: staging
    unh698_image_version: xxxxxxx
    unh698_host_port: xxxxxxx
    unh698_container_port: xxxxxxx
  roles:
    - unh698
  